### ISSUE TITLE
Package in conda-forge?

### ISSUE THREAD

**Issue by hadim** [pytorch/builder#190]
Any chance to get the conda recipes you have here moved to conda-forge?

That would allow creating conda-forge packages that depend on pytorch 1.0 or greater.

I can make a PR from the recipes you have in [conda/](./conda)  if you want.

**Comment by hadim** [comment]
I guess that would be important to have a conda-forge Cuda package first: https://github.com/conda-forge/staged-recipes/pull/6240

But you could still create the recipe now for pytorch-cpu and enable the GPU build when this cuda PR is merged.

**Comment by hadim** [comment]
As for the differents Cuda version build, the new build variants of conda 3.0 could be used: https://conda.io/docs/user-guide/tasks/build-packages/variants.html.

One recipe will be sufficient to build all the different packages.

**Comment by hadim** [comment]
That would also allow building pytorch with a CentOS6 glibc version (often default on universities cluster unfortunately...).

Ping @pjh5

**Comment by soumith** [comment]
we dont expect to be in conda-forge for some time for various reasons:

- one is staffing, we are quite low-staffed on the builds right now, and cannot maintain SLAs for conda-forge changes that might be needed
- the second is that our builds take several hours on 40-core powerful servers, they take 3x more time on Azure pipelines and Travis machines (we build the binaries for 7 CUDA architectures which is what makes them so long)
- the third is that CuDNN and NCCL often have known bugs that are not fixed until the next release cycle (months away), so we are very particular about controlling our versions and statically linking them for these libraries, which is not in `conda-forge` spirit
- the fourth is that we dont have stable builds yet, and we need to be in control of our destiny for a bit and keep tweaking things several times before we get to a working stable binary, so we prefer to control our build scripts tightly and push to them quickly

Also we cannot build on CentOS6
- because it's default shipped libstdc++ has a bug that we run into.
- various CUDA bits are almost not supported on CentOS6

We used to build (and I took various pains to make sure binaries until 0.3.0 are built on CentOS6), but at some point we had big blockers that we ran into, and I gave up and switched to CentOS7. Thankfully universities are now largely switching to CentOS7.
