### ISSUE TITLE
Replace dropbox and google drive links with s3 links

### ISSUE THREAD

**Issue by seemethere** [pytorch/builder#788]
https://github.com/pytorch/builder/blob/71a2b9aaf0b4d56a2b6048b92ba71858f3717dbb/windows/internal/cuda_install.bat#L174-L182

We should replace these dependencies with S3 assets, @peterjc123 do you know what's hosted on these?

cc @mszhanyi

**Comment by peterjc123** [comment]
`NvToolsExt.7z` is a collection of DLLs for the NVTX (CUDA).

`gpu_driver_dlls.7z` contains DLLs that serves as GPU drivers, should not be needed anymore.

**Comment by mszhanyi** [comment]
Today, [one nightly CI workflow](https://app.circleci.com/pipelines/github/pytorch/pytorch/374608/workflows/5810edd3-4785-4ad7-ab25-b7e53c976c84/jobs/15798967) is broken due to failed to downloading the gpu_driver_dlls.zip.
error 
![image](https://user-images.githubusercontent.com/16190118/131778998-54f67014-f4f4-44b6-898a-0758526272ee.png)

success
![image](https://user-images.githubusercontent.com/16190118/131779029-00c5ef5f-06dc-470c-8005-351288503bec.png)

**Comment by mszhanyi** [comment]
I tested that gpu_driver_dlls is only needed for cu102
https://github.com/pytorch/vision/pull/4058#discussion_r661956022

**Comment by peterjc123** [comment]
@mszhanyi Why we do need them?
